# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Use cargo to test the project
test:
    script:
        - rustc --version && cargo --version  # Print version info for debugging
        - cargo test --workspace --verbose

# Use cargo to create binary
deploy:
    stage: deploy
    script:
        - cargo --version  # Print version info for debugging
        - cargo build --release --verbose
    environment: production
    artifacts:
        paths: [ "target/release/alumina-compiler" ]
